FROM golang:1.16

ARG BOT_TOKEN_BUILD
ENV BOT_TOKEN=$BOT_TOKEN_BUILD
ARG COWIN_URL_BUILD
ENV COWIN_URL=$COWIN_URL_BUILD
ARG BOT_CHAT_ID_BUILD
ENV BOT_CHAT_ID=$BOT_CHAT_ID_BUILD

WORKDIR /app

COPY . /app

CMD ["go", "run", "main.go"]